log stderr all;

router id 172.30.0.2;

protocol device {
    scan time 10;
}

protocol static static_routes {
    ipv4;
    include "/generated/ru_routes.conf";
    include "/generated/custom_routes.conf";
}

protocol bgp to_frr {
    description "Internal BGP feed to FRR Front";
    local 172.30.0.2 as 65000;
    neighbor 172.30.0.3 as 65000;
    multihop;
    
    ipv4 {
        import none;
        export filter {
            if (65000, 1000) ~ bgp_community then {
                accept;
            }
            reject;
        };
    };
}
