frr version 8.4
frr defaults traditional
hostname public-bgp
no ipv6 forwarding
!
bgp community-list standard CL_ALLOW_PUBLIC permit 65000:1000
!
route-map RM_DENY_ALL deny 10
!
route-map RM_CORE_IN permit 10
 match community CL_ALLOW_PUBLIC
!
route-map RM_PUBLIC_OUT permit 10
 match community CL_ALLOW_PUBLIC
!
router bgp 65000
 bgp router-id 172.30.0.3
 no bgp default ipv4-unicast
 bgp no-rib
 !
 neighbor 172.30.0.2 remote-as 65000
 neighbor 172.30.0.2 description "Internal BIRD2 Core Feed"
 !
 neighbor PUBLIC peer-group
 neighbor PUBLIC description "Dynamic Public Clients"
 bgp listen range 0.0.0.0/0 peer-group PUBLIC
 !
 address-family ipv4 unicast
  neighbor 172.30.0.2 activate
  neighbor 172.30.0.2 route-map RM_CORE_IN in
  neighbor 172.30.0.2 route-map RM_DENY_ALL out
  !
  neighbor PUBLIC activate
  neighbor PUBLIC route-map RM_DENY_ALL in
  neighbor PUBLIC route-map RM_PUBLIC_OUT out
 exit-address-family
!
line vty
!
